import { sitePath } from "@/lib/sitePath";
import type {
    AuthorDTO,
    CourseDetailDTO,
    CourseListDTO,
    CourseMediaDTO,
    SiteDetailDTO,
    StudentDTO,
} from "./types";

const now = "2026-05-20T10:00:00Z";

export const demoMedia = (
    mediaAssetId: string,
    publicUrl: string,
    mediaRoleTypeName: string,
    mediaKind: string = "Image",
): CourseMediaDTO => ({
    mediaAssetId,
    storageKey: publicUrl,
    storageProvider: "Local",
    publicUrl: sitePath(publicUrl),
    mimeType: mediaKind === "Video" ? "video/mp4" : "image/jpeg",
    mediaKind,
    sizeBites: 0,
    createdAt: now,
    mediaRoleTypeId: mediaRoleTypeName,
    mediaRoleTypeName,
    mediaRoleTypeNameGeo: mediaRoleTypeName,
    sortOrder: 1,
});

export const mockAuthors: AuthorDTO[] = [
    {
        id: "author-nino",
        createdAt: now,
        firstName: "Nino",
        firstNameGeo: "ნინო",
        lastName: "Maisuradze",
        lastNameGeo: "მაისურაძე",
        title: "Clinical nutrition mentor",
        titleGeo: "კლინიკური კვების მენტორი",
        description:
            "Nutrition educator focused on evidence-based coaching, habit design, and practical meal planning.",
        descriptionGeo:
            "კვების მენტორი, რომელიც მუშაობს მტკიცებულებაზე დაფუძნებულ ქოუჩინგზე და პრაქტიკულ დაგეგმვაზე.",
        shortDescription: "Nutrition educator and academy mentor.",
        shortDescriptionGeo: "კვების მენტორი და აკადემიის ლექტორი.",
        coverUrl: sitePath("/images/poster/courses_photo.jpg"),
        backgroundUrl: sitePath("/images/backgrounds/students-together.jpeg"),
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        playlistUrl: null,
        version: 1,
        socialLinks: [
            {
                id: "author-nino-instagram",
                linkTypeId: "instagram",
                linkTypeName: "Instagram",
                linkUrl: "https://instagram.com/m.rnutrition",
                title: "Instagram",
                titleGeo: "Instagram",
                sortOrder: 1,
                version: 1,
            },
        ],
        educationRecords: [
            {
                id: "edu-author-nino",
                ownerType: "Author",
                ownerId: "author-nino",
                title: "MSc Nutrition Science",
                titleGeo: "მაგისტრი კვების მეცნიერებაში",
                description: "Applied nutrition and coaching practice.",
                descriptionGeo: "პრაქტიკული კვება და ქოუჩინგი.",
                startDate: "2018-09-01",
                endDate: "2020-06-01",
                version: 1,
                sortOrder: 1,
            },
        ],
        languageRecords: [],
        professionRecords: [],
        workExperienceRecords: [],
        districtRecords: [],
        media: [demoMedia("author-nino-cover", "/images/poster/courses_photo.jpg", "AuthorThumbnail")],
    },
];

const courseSections = [
    {
        id: "section-basics",
        order: 1,
        heading: "Nutrition foundations",
        headingGeo: "კვების საფუძვლები",
        paragraph:
            "Macros, calories, hydration, and how to translate nutrition theory into daily decisions.",
        paragraphGeo:
            "მაკროები, კალორიები, ჰიდრატაცია და კვების თეორიის ყოველდღიურ გადაწყვეტილებებად გადაქცევა.",
        coverUrl: sitePath("/images/courses/course1.jpg"),
        version: 1,
    },
    {
        id: "section-coaching",
        order: 2,
        heading: "Client coaching",
        headingGeo: "კლიენტის ქოუჩინგი",
        paragraph:
            "Assessment templates, progress tracking, and communication patterns for sustainable results.",
        paragraphGeo:
            "შეფასების ფორმები, პროგრესის კონტროლი და კომუნიკაცია მდგრადი შედეგებისთვის.",
        coverUrl: sitePath("/images/courses/course1.jpg"),
        version: 1,
    },
    {
        id: "section-practice",
        order: 3,
        heading: "Practical cases",
        headingGeo: "პრაქტიკული ქეისები",
        paragraph:
            "Realistic case studies for weight management, body recomposition, and health-focused goals.",
        paragraphGeo:
            "რეალისტური ქეისები წონის მართვისთვის, სხეულის კომპოზიციისთვის და ჯანმრთელობის მიზნებისთვის.",
        coverUrl: sitePath("/images/courses/course1.jpg"),
        version: 1,
    },
];

export const mockCourses: CourseDetailDTO[] = [
    {
        id: "nutrition-coach",
        createdAt: "2026-05-19T10:00:00Z",
        courseTypeId: "paid",
        courseType: "Paid",
        courseTypeGeo: "ფასიანი",
        courseName: "Nutrition Coach Certification",
        courseNameGeo: "კვების ქოუჩის სერტიფიცირება",
        description:
            "A complete certification-style program for future nutrition coaches, combining theory, case work, and client communication.",
        descriptionGeo:
            "სრული სასერტიფიკაციო პროგრამა მომავალი კვების ქოუჩებისთვის, თეორიით, ქეისებით და კლიენტთან კომუნიკაციით.",
        shortDescription: "A complete pathway for future nutrition coaches.",
        shortDescriptionGeo: "სრული გზა მომავალი კვების ქოუჩებისთვის.",
        price: 690,
        priceCurrency: "GEL",
        priceGEL: 690,
        priceUSD: 260,
        status: "Active",
        statusGeo: "აქტიური",
        certificationTypeId: "certificate",
        certificationTypeName: "Certificate",
        certificationTypeNameGeo: "სერტიფიკატი",
        version: 1,
        authors: mockAuthors,
        author: mockAuthors[0],
        courseMaterials: {
            id: "materials-nutrition-coach",
            coverUrl: sitePath("/images/courses/course1.jpg"),
            backgroundUrl: sitePath("/images/courses/course1.jpg"),
            videoUrl: null,
            syllabusUrl: sitePath("/pdfs/course-syllabus.pdf"),
            sections: courseSections,
            media: [
                demoMedia("course-cover-1", "/images/courses/course1.jpg", "CourseCover"),
                demoMedia("course-bg-1", "/images/courses/course1.jpg", "CourseBackground"),
                demoMedia("course-pdf-1", "/pdfs/course-syllabus.pdf", "CourseSyllabus", "Document"),
            ],
        },
    },
    {
        id: "meal-planning",
        createdAt: "2026-04-12T10:00:00Z",
        courseTypeId: "mini",
        courseType: "Mini",
        courseTypeGeo: "მინი",
        courseName: "Meal Planning Mini Course",
        courseNameGeo: "კვების დაგეგმვის მინი კურსი",
        description:
            "A focused mini course for building weekly menus, shopping systems, and balanced plates.",
        descriptionGeo:
            "მოკლე კურსი კვირის მენიუსთვის, საყიდლების სისტემისთვის და დაბალანსებული თეფშისთვის.",
        shortDescription: "Weekly menus, shopping lists, and balanced plates.",
        shortDescriptionGeo: "კვირის მენიუები, სიები და დაბალანსებული თეფში.",
        price: 120,
        priceCurrency: "GEL",
        priceGEL: 120,
        priceUSD: 45,
        status: "Active",
        statusGeo: "აქტიური",
        certificationTypeId: "completion",
        certificationTypeName: "Completion",
        certificationTypeNameGeo: "დასრულება",
        version: 1,
        authors: mockAuthors,
        author: mockAuthors[0],
        courseMaterials: {
            id: "materials-meal-planning",
            coverUrl: sitePath("/images/courses/course5.jpg"),
            backgroundUrl: sitePath("/images/courses/course5.jpg"),
            videoUrl: null,
            syllabusUrl: sitePath("/pdfs/course-syllabus.pdf"),
            sections: courseSections,
            media: [
                demoMedia("course-cover-2", "/images/courses/course5.jpg", "CourseCover"),
                demoMedia("course-bg-2", "/images/courses/course5.jpg", "CourseBackground"),
            ],
        },
    },
];

export const mockCourseList: CourseListDTO[] = mockCourses.map((course) => ({
    id: course.id,
    createdAt: course.createdAt,
    courseTypeId: course.courseTypeId,
    courseType: course.courseType,
    courseTypeGeo: course.courseTypeGeo,
    courseName: course.courseName,
    courseNameGeo: course.courseNameGeo,
    shortDescription: course.shortDescription,
    shortDescriptionGeo: course.shortDescriptionGeo,
    price: course.price,
    priceCurrency: course.priceCurrency,
    priceGEL: course.priceGEL,
    priceUSD: course.priceUSD,
    status: course.status,
    statusGeo: course.statusGeo,
    certificationTypeId: course.certificationTypeId,
    certificationTypeName: course.certificationTypeName,
    certificationTypeNameGeo: course.certificationTypeNameGeo,
    coverUrl: course.courseMaterials?.coverUrl ?? sitePath("/images/courses/course1.jpg"),
    version: course.version,
}));

export const mockStudents: StudentDTO[] = [
    {
        id: "mariam-gelashvili",
        createdAt: "2026-03-15T10:00:00Z",
        userId: null,
        firstName: "Mariam",
        firstNameGeo: "მარიამ",
        lastName: "Gelashvili",
        lastNameGeo: "გელაშვილი",
        title: "Certified nutrition coach",
        titleGeo: "სერტიფიცირებული კვების ქოუჩი",
        sex: "female",
        sexTypeId: "female",
        sexTypeName: "Female",
        sexTypeNameGeo: "ქალი",
        gender: "Female",
        genderGeo: "ქალი",
        birthDate: "1998-06-12",
        age: 27,
        email: "mariam@example.com",
        phoneNumber: "+995 555 12 34 56",
        about:
            "Mariam works with beginner clients on flexible nutrition, healthy routines, and confidence around food.",
        aboutGeo:
            "მარიამი მუშაობს დამწყებ კლიენტებთან მოქნილ კვებაზე, ჯანსაღ რუტინებზე და საკვების მიმართ თავდაჯერებაზე.",
        description:
            "Mariam works with beginner clients on flexible nutrition, healthy routines, and confidence around food.",
        descriptionGeo:
            "მარიამი მუშაობს დამწყებ კლიენტებთან მოქნილ კვებაზე, ჯანსაღ რუტინებზე და საკვების მიმართ თავდაჯერებაზე.",
        emailVisible: true,
        phoneVisible: true,
        academyFavourite: true,
        featured: true,
        certificationType: "Certified nutrition coach",
        certificationTypeGeo: "სერტიფიცირებული კვების ქოუჩი",
        socialLinks: [
            {
                id: "mariam-instagram",
                linkTypeId: "instagram",
                linkTypeName: "Instagram",
                linkUrl: "https://instagram.com/m.rnutrition",
                title: "Instagram",
                titleGeo: "Instagram",
                sortOrder: 1,
                version: 1,
            },
            {
                id: "mariam-youtube",
                linkTypeId: "youtube",
                linkTypeName: "YouTube",
                linkUrl: "https://www.youtube.com/@NutritionAcademyofGeorgia",
                title: "YouTube",
                titleGeo: "YouTube",
                sortOrder: 2,
                version: 1,
            },
        ],
        educationRecords: [
            {
                id: "mariam-edu",
                ownerType: "Student",
                ownerId: "mariam-gelashvili",
                title: "Nutrition Academy graduate",
                titleGeo: "Nutrition Academy-ის კურსდამთავრებული",
                sortOrder: 1,
                version: 1,
            },
            {
                id: "mariam-edu-2",
                ownerType: "Student",
                ownerId: "mariam-gelashvili",
                title: "Client psychology workshop",
                titleGeo: "კლიენტის ფსიქოლოგიის ვორქშოპი",
                description: "Habit change, motivation, and client communication.",
                descriptionGeo: "ჩვევების ცვლილება, მოტივაცია და კლიენტთან კომუნიკაცია.",
                startDate: "2026-01-15",
                endDate: "2026-02-15",
                sortOrder: 2,
                version: 1,
            },
        ],
        languageRecords: [
            {
                id: "mariam-lang",
                ownerType: "Student",
                ownerId: "mariam-gelashvili",
                languageTypeName: "Georgian, English",
                languageTypeNameGeo: "ქართული, ინგლისური",
                sortOrder: 1,
                version: 1,
            },
        ],
        professionRecords: [
            {
                id: "mariam-prof",
                ownerType: "Student",
                ownerId: "mariam-gelashvili",
                professionTypeName: "Nutrition coach",
                professionTypeNameGeo: "კვების ქოუჩი",
                sortOrder: 1,
                version: 1,
            },
        ],
        workExperienceRecords: [
            {
                id: "mariam-work",
                ownerType: "Student",
                ownerId: "mariam-gelashvili",
                workTypeName: "Private coaching",
                workTypeNameGeo: "ინდივიდუალური ქოუჩინგი",
                sortOrder: 1,
                version: 1,
            },
            {
                id: "mariam-work-2",
                ownerType: "Student",
                ownerId: "mariam-gelashvili",
                workTypeName: "Group nutrition challenges",
                workTypeNameGeo: "ჯგუფური კვების გამოწვევები",
                title: "Assistant coach",
                titleGeo: "ასისტენტი ქოუჩი",
                description: "Helped clients set weekly goals and track nutrition routines.",
                descriptionGeo: "ეხმარებოდა კლიენტებს კვირის მიზნებისა და კვების რუტინის კონტროლში.",
                startDate: "2026-03-01",
                endDate: "2026-05-01",
                sortOrder: 2,
                version: 1,
            },
        ],
        districtRecords: [
            {
                id: "mariam-district",
                ownerType: "Student",
                ownerId: "mariam-gelashvili",
                districtTypeName: "Tbilisi",
                districtTypeNameGeo: "თბილისი",
                sortOrder: 1,
                version: 1,
            },
        ],
        enrollments: [
            {
                id: "mariam-cert-1",
                courseName: "Nutrition Coach Certification",
                courseNameGeo: "კვების ქოუჩის სერტიფიცირება",
                certificationDate: "2026-02-20",
                validityPeriodInDays: 720,
                certificateMediaAssetId: "mariam-cert-media",
            },
            {
                id: "mariam-cert-2",
                courseName: "Meal Planning Mini Course",
                courseNameGeo: "კვების დაგეგმვის მინი კურსი",
                certificationDate: "2026-04-10",
                validityPeriodInDays: 365,
                certificateMediaAssetId: "mariam-cert-media-2",
            },
        ],
        media: [
            demoMedia("mariam-cover", "/images/backgrounds/students-together.jpeg", "StudentThumbnail"),
            demoMedia("mariam-cert-media", "/images/certificates/certificate1.jpg", "Certificate"),
            demoMedia("mariam-cert-media-2", "/images/certificates/certificate2.jpg", "Certificate"),
            {
                ...demoMedia("mariam-video", "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "StudentVideo", "Video"),
                publicUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            },
            {
                ...demoMedia("mariam-video-2", "https://www.youtube.com/watch?v=ysz5S6PUM-U", "StudentVideo", "Video"),
                publicUrl: "https://www.youtube.com/watch?v=ysz5S6PUM-U",
                sortOrder: 2,
            },
        ],
        coverUrl: sitePath("/images/backgrounds/students-together.jpeg"),
        version: 1,
    },
    {
        id: "dato-kapanadze",
        createdAt: "2026-02-08T10:00:00Z",
        userId: null,
        firstName: "Dato",
        firstNameGeo: "დავით",
        lastName: "Kapanadze",
        lastNameGeo: "კაპანაძე",
        title: "Sports nutrition student",
        titleGeo: "სპორტული კვების სტუდენტი",
        sex: "male",
        sexTypeId: "male",
        sexTypeName: "Male",
        sexTypeNameGeo: "კაცი",
        gender: "Male",
        genderGeo: "კაცი",
        birthDate: "1995-11-03",
        age: 30,
        email: "dato@example.com",
        phoneNumber: "+995 555 98 76 54",
        about: "Dato is focused on strength training nutrition and sustainable performance habits.",
        aboutGeo: "დავითი მუშაობს ძალოვანი ვარჯიშის კვებაზე და მდგრად ჩვევებზე.",
        description: "Dato is focused on strength training nutrition and sustainable performance habits.",
        descriptionGeo: "დავითი მუშაობს ძალოვანი ვარჯიშის კვებაზე და მდგრად ჩვევებზე.",
        emailVisible: true,
        phoneVisible: false,
        academyFavourite: false,
        featured: true,
        certificationType: "Sports nutrition student",
        certificationTypeGeo: "სპორტული კვების სტუდენტი",
        socialLinks: [
            {
                id: "dato-instagram",
                linkTypeId: "instagram",
                linkTypeName: "Instagram",
                linkUrl: "https://instagram.com/m.rnutrition",
                title: "Instagram",
                titleGeo: "Instagram",
                sortOrder: 1,
                version: 1,
            },
            {
                id: "dato-tiktok",
                linkTypeId: "tiktok",
                linkTypeName: "TikTok",
                linkUrl: "https://www.tiktok.com/@m.rnutrition",
                title: "TikTok",
                titleGeo: "TikTok",
                sortOrder: 2,
                version: 1,
            },
        ],
        educationRecords: [
            {
                id: "dato-edu-1",
                ownerType: "Student",
                ownerId: "dato-kapanadze",
                title: "Sports Nutrition Fundamentals",
                titleGeo: "სპორტული კვების საფუძვლები",
                description: "Fueling, recovery, hydration, and supplement basics.",
                descriptionGeo: "ენერგია, აღდგენა, ჰიდრატაცია და დანამატების საფუძვლები.",
                startDate: "2025-11-01",
                endDate: "2026-01-20",
                sortOrder: 1,
                version: 1,
            },
            {
                id: "dato-edu-2",
                ownerType: "Student",
                ownerId: "dato-kapanadze",
                title: "Strength training nutrition workshop",
                titleGeo: "ძალოვანი ვარჯიშის კვების ვორქშოპი",
                description: "Meal timing and recovery strategy for active clients.",
                descriptionGeo: "კვების დრო და აღდგენის სტრატეგია აქტიური კლიენტებისთვის.",
                startDate: "2026-02-05",
                endDate: "2026-03-05",
                sortOrder: 2,
                version: 1,
            },
        ],
        languageRecords: [
            {
                id: "dato-lang-1",
                ownerType: "Student",
                ownerId: "dato-kapanadze",
                languageTypeName: "Georgian",
                languageTypeNameGeo: "ქართული",
                sortOrder: 1,
                version: 1,
            },
            {
                id: "dato-lang-2",
                ownerType: "Student",
                ownerId: "dato-kapanadze",
                languageTypeName: "English",
                languageTypeNameGeo: "ინგლისური",
                sortOrder: 2,
                version: 1,
            },
        ],
        professionRecords: [
            {
                id: "dato-prof-1",
                ownerType: "Student",
                ownerId: "dato-kapanadze",
                professionTypeName: "Fitness nutrition consultant",
                professionTypeNameGeo: "ფიტნეს კვების კონსულტანტი",
                sortOrder: 1,
                version: 1,
            },
            {
                id: "dato-prof-2",
                ownerType: "Student",
                ownerId: "dato-kapanadze",
                professionTypeName: "Personal trainer",
                professionTypeNameGeo: "პერსონალური მწვრთნელი",
                sortOrder: 2,
                version: 1,
            },
        ],
        workExperienceRecords: [
            {
                id: "dato-work-1",
                ownerType: "Student",
                ownerId: "dato-kapanadze",
                workTypeName: "Gym client support",
                workTypeNameGeo: "დარბაზის კლიენტების მხარდაჭერა",
                title: "Nutrition assistant",
                titleGeo: "კვების ასისტენტი",
                description: "Built simple meal routines for strength training clients.",
                descriptionGeo: "ქმნიდა მარტივ კვების რუტინებს ძალოვანი ვარჯიშის კლიენტებისთვის.",
                startDate: "2026-01-01",
                endDate: "2026-05-01",
                sortOrder: 1,
                version: 1,
            },
        ],
        districtRecords: [
            {
                id: "dato-district-1",
                ownerType: "Student",
                ownerId: "dato-kapanadze",
                districtTypeName: "Batumi",
                districtTypeNameGeo: "ბათუმი",
                sortOrder: 1,
                version: 1,
            },
        ],
        enrollments: [
            {
                id: "dato-cert-1",
                courseName: "Sports Nutrition Fundamentals",
                courseNameGeo: "სპორტული კვების საფუძვლები",
                certificationDate: "2026-03-18",
                validityPeriodInDays: 540,
                certificateMediaAssetId: "dato-cert-media",
            },
            {
                id: "dato-cert-2",
                courseName: "Meal Planning Mini Course",
                courseNameGeo: "კვების დაგეგმვის მინი კურსი",
                certificationDate: "2026-04-28",
                validityPeriodInDays: 365,
                certificateMediaAssetId: "dato-cert-media-2",
            },
        ],
        media: [
            demoMedia("dato-cover", "/images/backgrounds/students-together.jpeg", "StudentThumbnail"),
            demoMedia("dato-cert-media", "/images/certificates/certificate1.jpg", "Certificate"),
            demoMedia("dato-cert-media-2", "/images/certificates/certificate2.jpg", "Certificate"),
            {
                ...demoMedia("dato-video", "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "StudentVideo", "Video"),
                publicUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            },
            {
                ...demoMedia("dato-video-2", "https://www.youtube.com/watch?v=ysz5S6PUM-U", "StudentVideo", "Video"),
                publicUrl: "https://www.youtube.com/watch?v=ysz5S6PUM-U",
                sortOrder: 2,
            },
        ],
        coverUrl: sitePath("/images/backgrounds/students-together.jpeg"),
        version: 1,
    },
];

export const mockSiteDetails: SiteDetailDTO[] = [
    {
        id: "site-main",
        pageTypeId: "main",
        pageTypeName: "main",
        pageTypeNameGeo: "მთავარი",
        createdAt: now,
        title: "Mr. Nutrition Academy",
        titleGeo: "Mr. Nutrition Academy",
        titleColor: "#ffffff",
        subtitle: "Practical nutrition education for coaches, students, and wellness professionals.",
        subtitleColor: "#ffffff",
        subtitleGeo: "პრაქტიკული კვების განათლება ქოუჩებისთვის, სტუდენტებისთვის და პროფესიონალებისთვის.",
        version: 1,
        backgroundUrl: sitePath("/images/poster/poster.jpg"),
        videoUrl: null,
        media: [
            demoMedia("site-main-bg", "/images/poster/poster.jpg", "SiteDetailBackground"),
        ],
    },
    {
        id: "site-courses",
        pageTypeId: "courses",
        pageTypeName: "courses",
        pageTypeNameGeo: "კურსები",
        createdAt: now,
        title: "Courses built for real coaching",
        titleGeo: "კურსები რეალური ქოუჩინგისთვის",
        titleColor: "#ffffff",
        subtitle: "Explore certification and short-format programs.",
        subtitleColor: "#ffffff",
        subtitleGeo: "დაათვალიერე სასერტიფიკაციო და მოკლე პროგრამები.",
        version: 1,
        backgroundUrl: sitePath("/images/poster/courses_photo.jpg"),
        videoUrl: null,
        media: [demoMedia("site-courses-bg", "/images/poster/courses_photo.jpg", "SiteDetailBackground")],
    },
    {
        id: "site-students",
        pageTypeId: "students",
        pageTypeName: "students",
        pageTypeNameGeo: "სტუდენტები",
        createdAt: now,
        title: "Meet our students",
        titleGeo: "გაიცანი ჩვენი სტუდენტები",
        titleColor: "#ffffff",
        subtitle: "A preview of academy graduates and their portfolios.",
        subtitleColor: "#ffffff",
        subtitleGeo: "აკადემიის კურსდამთავრებულების და მათი პორტფოლიოების პრევიუ.",
        version: 1,
        backgroundUrl: sitePath("/images/backgrounds/students-together.jpeg"),
        videoUrl: null,
        media: [demoMedia("site-students-bg", "/images/backgrounds/students-together.jpeg", "SiteDetailBackground")],
    },
];

export const mockYouTubeChannels = [
    {
        key: "mrNutrition" as const,
        href: "https://www.youtube.com/@MrNutrition1",
        channelTitle: "Mr. Nutrition",
        latestVideoTitle: "Nutrition coaching basics",
        latestVideoUrl: "https://www.youtube.com/@MrNutrition1",
        latestVideoPublished: "2026-05-01T10:00:00Z",
        latestVideoThumbnail: sitePath("/images/poster/courses_photo.jpg"),
        channelAvatar: sitePath("/images/logos/site_logo_green.png"),
    },
    {
        key: "nutritionAcademy" as const,
        href: "https://www.youtube.com/@NutritionAcademyofGeorgia",
        channelTitle: "Nutrition Academy of Georgia",
        latestVideoTitle: "Student portfolio preview",
        latestVideoUrl: "https://www.youtube.com/@NutritionAcademyofGeorgia",
        latestVideoPublished: "2026-04-18T10:00:00Z",
        latestVideoThumbnail: sitePath("/images/backgrounds/students-together.jpeg"),
        channelAvatar: sitePath("/images/logos/site_logo.png"),
    },
];
